version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
      - aws --version

  pre_build:
    commands:
      - echo Pre-build phase...
      - echo "NODE_ENV=production" >> .env
      - echo "REACT_APP_CREDENTIALS_API_URL=$REACT_APP_CREDENTIALS_API_URL" >> .env
      - echo "REACT_APP_AWS_REGION=$REACT_APP_AWS_REGION" >> .env
      - echo "REACT_APP_S3_BUCKET_NAME=$REACT_APP_S3_BUCKET_NAME" >> .env
      - echo "REACT_APP_GOOGLE_CLIENT_ID=$REACT_APP_GOOGLE_CLIENT_ID" >> .env
      - echo Environment variables set

  build:
    commands:
      - echo Building the React application...
      - npm run build
      - echo Build completed

  post_build:
    commands:
      - echo Deploying to S3 bucket...
      - aws s3 sync build/ s3://dee-en-eh-react-app --delete
      - aws cloudfront create-invalidation --distribution-id E3QB86OHQX5C36 --paths "/*"
      - echo Deployment completed

artifacts:
  base-directory: build
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'